services:
  app:
    build:
      context: ./workspace/docker/php8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    extra_hosts:
      - 'integrations.thesalesmachine.test:host-gateway'
    environment:
      WWWUSER: '${WWWUSER}'
      XDEBUG_MODE: '${CLUSTER_INTEGRATIONS_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${CLUSTER_INTEGRATIONS_XDEBUG_CONFIG:-client_host=integrations.cluster.test}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - './:/var/www/html'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '8000:80'
    networks:
      - cluster-integrations-net
    depends_on:
      - redis
      - mailhog
      - mongo

  mongo:
    image: 'mongo'
    command: ["mongod", "--replSet", "dev", "--bind_ip_all", "--port", "27017", "--keyFile", "/data/replicaset.key"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGODB_USERNAME:-dbuser}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGODB_PASSWORD:-password}'
    volumes:
      - 'cluster-integrations-mongodb:/data/mdb'
      - './workspace/docker/mongodb/replicaset.key:/data/replicaset.dev.key'
    entrypoint:
      - bash
      - -c
      - |
        cp /data/replicaset.dev.key /data/replicaset.key
        chmod 400 /data/replicaset.key
        chown 999:999 /data/replicaset.key
        exec docker-entrypoint.sh $$@
    ports:
      - '${CLUSTER_INTEGRATIONS_MONGO_PORT:-27017}:27017'
    networks:
      - cluster-integrations-net

  redis:
    image: 'redis:alpine'
    ports:
      - '${CLUSTER_INTEGRATIONS_REDIS_PORT:-63790}:6379'
    volumes:
      - 'cluster-integrations-redis:/data'
    networks:
      - cluster-integrations-net
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${CLUSTER_INTEGRATIONS_MAILHOG_DASHBOARD_PORT:-9025}:8025'
    networks:
      - cluster-integrations-net

networks:
  cluster-integrations-net:
    driver: bridge
volumes:
  cluster-integrations-redis:
    driver: local
  cluster-integrations-mongodb:
    driver: local
